// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUORPXSJMHVj4fFS2w7clpstR9mMzoK2A',
    appId: '1:827874579559:web:d80f965ae08e68250f30c2',
    messagingSenderId: '827874579559',
    projectId: 'fir-flutter-codelab-55e05',
    authDomain: 'fir-flutter-codelab-55e05.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-55e05.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1sY0WQOQ2_n1rPUb19_MAHyNvBrOW6Ig',
    appId: '1:827874579559:android:3974c4ff734d7aec0f30c2',
    messagingSenderId: '827874579559',
    projectId: 'fir-flutter-codelab-55e05',
    storageBucket: 'fir-flutter-codelab-55e05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0EU7df5Xcb1Z-_UJLgf87f4lK0lXb5Fg',
    appId: '1:827874579559:ios:4d295f854cb49c9e0f30c2',
    messagingSenderId: '827874579559',
    projectId: 'fir-flutter-codelab-55e05',
    storageBucket: 'fir-flutter-codelab-55e05.appspot.com',
    iosClientId: '827874579559-4pd88b64bvo0prvq475dvunsvs5a14a6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0EU7df5Xcb1Z-_UJLgf87f4lK0lXb5Fg',
    appId: '1:827874579559:ios:4d295f854cb49c9e0f30c2',
    messagingSenderId: '827874579559',
    projectId: 'fir-flutter-codelab-55e05',
    storageBucket: 'fir-flutter-codelab-55e05.appspot.com',
    iosClientId: '827874579559-4pd88b64bvo0prvq475dvunsvs5a14a6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
